version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: tasm
      POSTGRES_DB: tasm_code_safe
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=tasm
      - DB_PASS=password
      - PORT=8080

